In [2]:
import pandas as pd

In [4]:
database = pd.read_csv("annual-enterprise-survey-2020-financial-year-provisional-csv.csv")

In [6]:
database.head(5)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"733,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,872",ANZSIC06 divisions A-S (excluding classes K633...

In [7]:
database.tail(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
37070,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H32,Current liabilities,Financial position,"10,212","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37071,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H33,Other liabilities,Financial position,"2,220","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37072,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H34,Total income per employee count,Financial ratios,"523,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37073,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"17,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37074,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H36,Current ratio,Financial ratios,91,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [3]:
database.iloc[37077]

NameError: name 'database' is not defined

In [10]:
database.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [11]:
database.values

array([[2020, 'Level 1', '99999', ..., 'Financial performance',
        '733,258',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2020, 'Level 1', '99999', ..., 'Financial performance',
        '660,630',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2020, 'Level 1', '99999', ..., 'Financial performance', '54,342',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       ...,
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '12',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '5',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '46',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119']],
      dtype=object)

In [12]:
type(database.values)

numpy.ndarray

In [13]:
database.index

RangeIndex(start=0, stop=37080, step=1)

In [14]:
database

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"733,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [16]:
(database, index=['200','30000','250','277'])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (334424171.py, line 1)

In [21]:
database.iloc[200]

Year                                                   2020
Industry_aggregation_NZSIOC                         Level 3
Industry_code_NZSIOC                                   AA13
Industry_name_NZSIOC                   Dairy Cattle Farming
Units                                    Dollars (millions)
Variable_code                                           H30
Variable_name                  Total equity and liabilities
Variable_category                        Financial position
Value                                                68,503
Industry_code_ANZSIC06                  ANZSIC06 group A016
Name: 200, dtype: object

In [39]:
database.iloc[[3000, 2222]]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
3000,2020,Level 3,JJ11,Information Media Services,Dollars (millions),H21,Opening stocks,Financial performance,162,"ANZSIC06 groups J541, J542, J551, J552, J561, ..."
2222,2020,Level 4,FF116,Commission Based Wholesaling,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,16,ANZSIC06 Group F380

In [37]:
database.iloc[[1, 5, 20, 30]]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
5,2020,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,"32,730",ANZSIC06 divisions A-S (excluding classes K633...
20,2020,Level 1,99999,All industries,Dollars (millions),H30,Total equity and liabilities,Financial position,"2,396,143",ANZSIC06 divisions A-S (excluding classes K633...
30,2020,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,32,ANZSIC06 divisions A-S (excluding classes K633...

In [22]:
database.iloc[-1]

Year                                                                        2013
Industry_aggregation_NZSIOC                                              Level 3
Industry_code_NZSIOC                                                        ZZ11
Industry_name_NZSIOC                                  Food product manufacturing
Units                                                                 Percentage
Variable_code                                                                H41
Variable_name                                              Liabilities structure
Variable_category                                               Financial ratios
Value                                                                         46
Industry_code_ANZSIC06         ANZSIC06 groups C111, C112, C113, C114, C115, ...
Name: 37079, dtype: object

In [25]:
database['Industry_aggregation_NZSIOC']

0        Level 1
1        Level 1
2        Level 1
3        Level 1
4        Level 1
          ...
37075    Level 3
37076    Level 3
37077    Level 3
37078    Level 3
37079    Level 3
Name: Industry_aggregation_NZSIOC, Length: 37080, dtype: object

In [33]:
database[['Industry_name_NZSIOC','Units']]

             Industry_name_NZSIOC               Units
0                  All industries  Dollars (millions)
1                  All industries  Dollars (millions)
2                  All industries  Dollars (millions)
3                  All industries  Dollars (millions)
4                  All industries  Dollars (millions)
...                           ...                 ...
37075  Food product manufacturing          Percentage
37076  Food product manufacturing          Percentage
37077  Food product manufacturing          Percentage
37078  Food product manufacturing          Percentage
37079  Food product manufacturing          Percentage

[37080 rows x 2 columns]

In [30]:
database.iloc[37075]

Year                                                                        2013
Industry_aggregation_NZSIOC                                              Level 3
Industry_code_NZSIOC                                                        ZZ11
Industry_name_NZSIOC                                  Food product manufacturing
Units                                                                 Percentage
Variable_code                                                                H37
Variable_name                                                        Quick ratio
Variable_category                                               Financial ratios
Value                                                                         52
Industry_code_ANZSIC06         ANZSIC06 groups C111, C112, C113, C114, C115, ...
Name: 37075, dtype: object

In [40]:
l = database.iloc

In [41]:
l[240]

Year                                                                2020
Industry_aggregation_NZSIOC                                      Level 4
Industry_code_NZSIOC                                               AA141
Industry_name_NZSIOC           Poultry, Deer and Other Livestock Farming
Units                                                         Percentage
Variable_code                                                        H41
Variable_name                                      Liabilities structure
Variable_category                                       Financial ratios
Value                                                                 40
Industry_code_ANZSIC06              ANZSIC06 groups A017, A018, and A019
Name: 240, dtype: object

In [44]:
database['200': '400']

TypeError: cannot do slice indexing on RangeIndex with these indexers [200] of type str

In [46]:
Industry_code_NZSIOC * 1000

NameError: name 'Industry_code_NZSIOC' is not defined

In [47]:
database < 1000

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
database > 1000

In [49]:
database

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2020,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"733,258",ANZSIC06 divisions A-S (excluding classes K633...
1,2020,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"660,630",ANZSIC06 divisions A-S (excluding classes K633...
2,2020,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"54,342",ANZSIC06 divisions A-S (excluding classes K633...
3,2020,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"18,285",ANZSIC06 divisions A-S (excluding classes K633...
4,2020,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"654,872",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
37075,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37076,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37077,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37078,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
37079,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [68]:
Value < 44

NameError: name 'Value' is not defined

In [69]:
database.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [72]:
database.info

<bound method DataFrame.info of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999
1      2020                     Level 1                99999
2      2020                     Level 1                99999
3      2020                     Level 1                99999
4      2020                     Level 1                99999
...     ...                         ...                  ...
37075  2013                     Level 3                 ZZ11
37076  2013                     Level 3                 ZZ11
37077  2013                     Level 3                 ZZ11
37078  2013                     Level 3                 ZZ11
37079  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
37075  Food product manufacturing          Percentage           H37
37076  Food product manufacturing          Percentage           H38
37077  Food product manufacturing          Percentage           H39
37078  Food product manufacturing          Percentage           H40
37079  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
37075                                      Quick ratio       Financial ratios
37076              Margin on sales of goods for resale       Financial ratios
37077                                 Return on equity       Financial ratios
37078                           Return on total assets       Financial ratios
37079                            Liabilities structure       Financial ratios

         Value                             Industry_code_ANZSIC06
0      733,258  ANZSIC06 divisions A-S (excluding classes K633...
1      660,630  ANZSIC06 divisions A-S (excluding classes K633...
2       54,342  ANZSIC06 divisions A-S (excluding classes K633...
3       18,285  ANZSIC06 divisions A-S (excluding classes K633...
4      654,872  ANZSIC06 divisions A-S (excluding classes K633...
...        ...                                                ...
37075       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37076       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37077       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37078        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37079       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[37080 rows x 10 columns]>

In [73]:
database.index

RangeIndex(start=0, stop=37080, step=1)

In [74]:
database.shape

(37080, 10)

In [75]:
database.describe

<bound method NDFrame.describe of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2020                     Level 1                99999
1      2020                     Level 1                99999
2      2020                     Level 1                99999
3      2020                     Level 1                99999
4      2020                     Level 1                99999
...     ...                         ...                  ...
37075  2013                     Level 3                 ZZ11
37076  2013                     Level 3                 ZZ11
37077  2013                     Level 3                 ZZ11
37078  2013                     Level 3                 ZZ11
37079  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
37075  Food product manufacturing          Percentage           H37
37076  Food product manufacturing          Percentage           H38
37077  Food product manufacturing          Percentage           H39
37078  Food product manufacturing          Percentage           H40
37079  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
37075                                      Quick ratio       Financial ratios
37076              Margin on sales of goods for resale       Financial ratios
37077                                 Return on equity       Financial ratios
37078                           Return on total assets       Financial ratios
37079                            Liabilities structure       Financial ratios

         Value                             Industry_code_ANZSIC06
0      733,258  ANZSIC06 divisions A-S (excluding classes K633...
1      660,630  ANZSIC06 divisions A-S (excluding classes K633...
2       54,342  ANZSIC06 divisions A-S (excluding classes K633...
3       18,285  ANZSIC06 divisions A-S (excluding classes K633...
4      654,872  ANZSIC06 divisions A-S (excluding classes K633...
...        ...                                                ...
37075       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37076       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37077       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37078        5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
37079       46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[37080 rows x 10 columns]>

In [5]:
database.loc['200':'400']

NameError: name 'database' is not defined

In [5]:
database.head

NameError: name 'database' is not defined

In [8]:
database.head(10)

NameError: name 'database' is not defined